### ISSUE TITLE
Put data files into ~/.local/state

### ISSUE THREAD

**Issue by sunng87** [ylxdzsw/dssd#2]
`~/.config` is where configuration files stored, `~/.local/share/` matches what we designed to store.

**Comment by ylxdzsw** [comment]
Ok, can confirm that gnome-keyring stores the secrets in `~/.local/share/keyrings/`. I agree that we should follow this.

**Comment by sunng87** [comment]
I just realized there is new XGD directory called `XDG_STATE_HOME` designed to hold state and we'd better use that folder.

https://wiki.archlinux.org/title/XDG_Base_Directory

**Comment by ylxdzsw** [comment]
Sounds reasonable. I have change it to XDG_STATE_HOME in the last commit and released a new version. That's a breaking change but the alpha state of the project should be obvious so I think that fine.
