### ISSUE TITLE
choose a license and put it into the repo

### ISSUE THREAD

**Issue by jcgruenhage** [ylxdzsw/dssd#4]
o/

I'm packaging dssd at the moment, but I've noticed that it doesn't have a license yet. In the Rust world, dual licensing as Apache-2.0 and MIT is common, if you don't have a strong opinion on this yourself.

**Comment by ylxdzsw** [comment]
Thanks for your interest and effort! I have added a license (MIT) to the repository.

**Comment by jcgruenhage** [comment]
Great, thanks!
