### ISSUE TITLE
Not seems to work with github cli

### ISSUE THREAD

**Issue by sunng87** [ylxdzsw/dssd#5]
The `gh` seems to use SecretService to store token but with dssd I always get `no token found for xxxx` even if login success.

From dbus-monitor I can see error message like 

```
error time=1726791872.465235 sender=:1.56 -> destination=:1.1755 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=15
   string "Unknown method SearchItems"
```

Not sure if this is the root cause. I can spend some time to investigate but it would be nice if you are familiar with this issue

**Comment by ylxdzsw** [comment]
The error message suggests that it cannot find the `SearchItems` methods. Both `org.freedesktop.Secret.Service` and `org.freedesktop.Secret.Collection` have that method, but DSSD only implemented for the former. Perhaps `gh` was calling `SearchItems` on `Collection`. I will look into it.

Thanks for the report.

**Comment by ylxdzsw** [comment]
I have added that method and tested `gh`. It works for me now.

**Comment by sunng87** [comment]
I confirm it works. Thank you so much for fast response!
